# -*- coding: utf-8 -*-
"""LatinSquare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doH_QDTJd-ZBc3cYAt5xa9djON7kErCf
"""

"""
generate_blocks.py
==================

Generates the fixed set of trial blocks for the difficulty-assignment
experiment, one set per US Census region, for use with reVISit's
pre-specified block lists.

------------------------------------------------------------------------------
WHAT A BLOCK IS
------------------------------------------------------------------------------
A block is 4 trials. It names four *different* states from one region and
assigns each of them a different difficulty level (1, 2, 3, 4). We represent a
block as an ordered 4-tuple, where position i holds the state shown at
difficulty level i+1:

    ("SD", "IL", "ND", "IA")
      ^     ^     ^     ^
      L1    L2    L3    L4

------------------------------------------------------------------------------
THE BALANCE PROPERTY WE GUARANTEE
------------------------------------------------------------------------------
Across the full set of blocks for a region, every state appears at every
difficulty level exactly once. So each state is used 4 times total, once per
level, and no state is systematically "the easy one" or "the hard one."

------------------------------------------------------------------------------
WHY THE SET HAS EXACTLY n BLOCKS (n = number of states in the region)
------------------------------------------------------------------------------
Every block assigns each of the 4 levels to exactly one state. So across b
blocks, level 1 is handed out exactly b times. Splitting those b assignments
equally among n states requires b/n per state, which forces n to divide b.
The smallest positive option is b = n, and it is always achievable.

At b = n, each state appears exactly once per level. This is precisely a
4 x n LATIN RECTANGLE: a 4-row, n-column array where every row is a
permutation of the n states (that gives level balance) and no state repeats
within a column (that makes each block four *distinct* states).

    rows    = difficulty levels 1..4
    columns = blocks

So "generate a minimal balanced block set" and "generate a random 4 x n Latin
rectangle" are the same task. That is the whole method, and it is one sentence
in a paper.

------------------------------------------------------------------------------
ONE REFINEMENT: WHICH LATIN RECTANGLE
------------------------------------------------------------------------------
Many Latin rectangles satisfy the balance property, and they are not equally
good. The textbook cyclic one -- block j = (state j, j+1, j+2, j+3) mod n --
is balanced but degenerate: consecutive states always co-occur and always sit
one level apart, while distant states never appear together at all. That is an
avoidable confound.

Since b = n blocks supply only 6n state-pair slots for n(n-1)/2 possible
pairs, we cannot equalize co-occurrence at this size (and we are not trying
to -- rough balance is the goal). We simply avoid the degenerate case: we draw
many random Latin rectangles and keep the one whose pair co-occurrence counts
are most evenly spread. Minimizing the sum of squared pair counts is
equivalent to minimizing their variance, because the total is fixed at 6n.

------------------------------------------------------------------------------
USAGE
------------------------------------------------------------------------------
    python generate_blocks.py            # writes blocks.csv, prints a report

    from generate_blocks import generate_region_blocks, CENSUS_REGIONS
    blocks = generate_region_blocks(CENSUS_REGIONS["West"], seed=1)

Output is deterministic given `seed`, so the block set is reproducible from
the seed reported in the paper.
"""

import csv
import random
from collections import Counter
from itertools import combinations


# =============================================================================
# Region definitions (4 standard US Census regions, 50 states)
# =============================================================================
# To include DC, append "DC" to South. To use the 9 Census *divisions*
# instead, replace this dict -- nothing else in the file needs to change.

CENSUS_REGIONS = {
    "Northeast": ["CT", "ME", "MA", "NH", "RI", "VT", "NJ", "NY", "PA"],
    "Midwest":   ["IL", "IN", "IA", "KS", "MI", "MN",
                  "MO", "NE", "ND", "OH", "SD", "WI"],
    "South":     ["AL", "AR", "FL", "GA", "KY", "LA", "MD", "MS",
                  "NC", "OK", "SC", "TN", "TX", "VA", "WV"],
    "West":      ["AZ", "CA", "CO", "ID", "MT", "NV",
                  "NM", "OR", "UT", "WA", "WY"],
}

# NOTE ON THE POOLS
# -----------------
# These are the 47 states that have stimuli in this study, NOT all 50. The
# exclusions are deliberate and must not be "fixed":
#
#   DE  no data generated. Delaware has exactly 3 counties, and the task asks
#       participants to choose exactly 3 -- the trial would be degenerate.
#   HI  no data generated.
#   AK  data exists in assets/Data/ but the state is excluded from the study.
#
# Adding any of them here produces component references such as hom_SO_DE_1
# that do not exist in the config, and blocks_to_revisit.py will refuse to
# write the config.

N_LEVELS = 4   # difficulty levels 1..4; also the number of trials per block


# =============================================================================
# Step 1: build one random Latin rectangle
# =============================================================================

def _random_row(n, used_in_column, rng, max_repairs=2000):
    """Return a random permutation of 0..n-1 that avoids per-column conflicts.

    `used_in_column[j]` is the set of state indices already placed in column j
    by earlier rows. We need a permutation `row` with row[j] not in
    used_in_column[j] for every j.

    Method: shuffle, then repeatedly fix violations by swapping a conflicting
    position with a random other position. Swapping preserves the
    permutation property, so we only ever need to check the conflict
    condition. Returns None if it fails to converge (caller retries).
    """
    row = list(range(n))
    rng.shuffle(row)

    for _ in range(max_repairs):
        conflicts = [j for j in range(n) if row[j] in used_in_column[j]]
        if not conflicts:
            return row
        j = rng.choice(conflicts)
        k = rng.randrange(n)
        row[j], row[k] = row[k], row[j]

    return None


def _random_latin_rectangle(n, rng, max_attempts=200):
    """Build a 4 x n Latin rectangle as a list of 4 rows of state indices.

    Row r is the assignment of states to blocks at difficulty level r+1.
    Each row is a permutation of all n states (level balance), and each
    column holds 4 distinct states (a valid block).
    """
    if n < N_LEVELS:
        raise ValueError(f"region has {n} states; need at least {N_LEVELS}")

    for _ in range(max_attempts):
        rows = []
        used_in_column = [set() for _ in range(n)]
        ok = True

        for _ in range(N_LEVELS):
            row = _random_row(n, used_in_column, rng)
            if row is None:
                ok = False
                break
            rows.append(row)
            for j, s in enumerate(row):
                used_in_column[j].add(s)

        if ok:
            return rows

    raise RuntimeError(f"failed to build a Latin rectangle for n={n}")


# =============================================================================
# Step 2: score candidates and keep the best
# =============================================================================

def _pair_counts(blocks):
    """Co-occurrence count for every state pair appearing in the block set."""
    counts = Counter()
    for block in blocks:
        for pair in combinations(sorted(block), 2):
            counts[pair] += 1
    return counts


def _score(blocks, n):
    """Lower is better, compared lexicographically as (zeros, sum_of_squares).

    sum_of_squares is the original criterion: total co-occurrences are fixed at
    6 * len(blocks) regardless of the rectangle, so minimising the sum of squares
    minimises the variance of the counts -- it spreads pairings as evenly as the
    block count allows and rejects degenerate rectangles like the cyclic one.

    zeros (the number of state pairs that never share a block) is added ahead of
    it as a tiebreak. Sum of squares already penalises zeros indirectly, but not
    decisively, and a pair that never co-occurs anywhere is the one outcome worth
    ruling out explicitly when it is reachable at all.

    It often is NOT reachable. b blocks supply only 6b pair slots against
    n(n-1)/2 possible pairs, so whenever n(n-1)/2 > 6b some pairs must be zero.
    At k=1 that bites for n > 13: the 15-state South has 90 slots for 105 pairs,
    forcing at least 15 zeros no matter what. In those regions this key simply
    selects candidates sitting at the mathematical floor.
    """
    counts = _pair_counts(blocks)
    observed = [counts.get(p, 0) for p in combinations(range(n), 2)]
    zeros = sum(1 for v in observed if v == 0)
    return (zeros, sum(v * v for v in observed))


def generate_region_blocks(states, seed=0, n_candidates=500, k=1):
    """Return a balanced block set for one region.

    Args:
        states:       list of state abbreviations in the region
        seed:         RNG seed; the same seed always reproduces the same set
        n_candidates: how many random block sets to try before picking
        k:            how many Latin rectangles to stack. k=1 gives the minimal
                      balanced set (n blocks, each state once per level). k=2
                      gives 2n blocks with each state twice per level, and so on.

    Returns:
        list of k*n tuples, each ("L1 state", "L2 state", "L3 state", "L4 state")

    On choosing k: participants draw one block per region, and reVISit hands
    them out in balanced sweeps of the whole set. Exposure is exactly balanced
    only when a sweep completes, so a set of k*n blocks is exactly balanced every
    k*n participants and ragged in between. Small k therefore means more frequent
    exact-balance checkpoints; large k means more distinct blocks and better pair
    coverage. Mean exposure per (state, level) cell is participants/n either way,
    so k buys variety, never statistical power. Keep k*n well under the number of
    participants per condition.
    """
    n = len(states)
    rng = random.Random(seed)

    best_blocks, best_score = None, None
    for _ in range(n_candidates):
        blocks = []
        seen = set()
        for _ in range(k):
            # Redraw a whole rectangle if it repeats a block already placed.
            # Individual blocks cannot be swapped out without breaking the
            # permutation property that the level balance rests on.
            for _attempt in range(200):
                rows = _random_latin_rectangle(n, rng)
                cand = [tuple(rows[r][j] for r in range(N_LEVELS))
                        for j in range(n)]
                if not any(b in seen for b in cand) and len(set(cand)) == n:
                    seen.update(cand)
                    blocks.extend(cand)
                    break
            else:
                raise RuntimeError(f"could not place rectangle without duplicates (n={n}, k={k})")

        score = _score(blocks, n)
        if best_score is None or score < best_score:
            best_blocks, best_score = blocks, score

    return [tuple(states[i] for i in block) for block in best_blocks]


# =============================================================================
# Step 3: verification -- always run this before using a block set
# =============================================================================

def verify(blocks, states, k=1):
    """Check the guarantees. Returns a dict; `balanced` must be True."""
    n = len(states)
    level_counts = Counter()
    for block in blocks:
        assert len(set(block)) == N_LEVELS, "block repeats a state"
        for level, state in enumerate(block, start=1):
            level_counts[(state, level)] += 1

    per_cell = {level_counts.get((s, l), 0)
                for s in states for l in range(1, N_LEVELS + 1)}

    pair_counts = Counter()
    for block in blocks:
        for pair in combinations(sorted(block), 2):
            pair_counts[pair] += 1
    observed = [pair_counts.get(p, 0) for p in combinations(sorted(states), 2)]

    return {
        "n_states": n,
        "n_blocks": len(blocks),
        "balanced": per_cell == {k},         # each state k times at each level
        "appearances_per_state": N_LEVELS * k,
        "pair_cooccurrence_range": (min(observed), max(observed)),
    }


# =============================================================================
# Step 4: export for reVISit
# =============================================================================

def write_csv(all_blocks, path="blocks.csv"):
    """One row per block: region, block index, and the four states by level."""
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["region", "block_id", "level_1", "level_2",
                    "level_3", "level_4"])
        for region, blocks in all_blocks.items():
            for i, block in enumerate(blocks):
                w.writerow([region, f"{region}_{i:02d}", *block])


def main(seed=1, out="blocks.csv", k=1):
    all_blocks = {}
    print(f"seed = {seed}   k = {k}\n")
    for region, states in CENSUS_REGIONS.items():
        blocks = generate_region_blocks(states, seed=seed, k=k)
        all_blocks[region] = blocks
        v = verify(blocks, states, k=k)
        assert v["balanced"], f"{region} failed verification"
        print(f"{region:<10} {v['n_states']:>2} states -> "
              f"{v['n_blocks']:>2} blocks | each state {k}x per level | "
              f"pair co-occurrence {v['pair_cooccurrence_range']}")

    write_csv(all_blocks, out)
    total = sum(len(b) for b in all_blocks.values())
    print(f"\n{total} blocks ({total * N_LEVELS} trials) written to {out}")
    return all_blocks


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--k", type=int, default=1)
    ap.add_argument("--out", default="blocks.csv")
    a = ap.parse_args()
    main(seed=a.seed, out=a.out, k=a.k)